title: "名古屋中学校・高等学校 鉄道研究部"
description: "名古屋中学校・高等学校 鉄道研究部の公式サイト"
lang: ja
markdown: kramdown
collections:
  activities:
    output: true
    permalink: /activity/:name/
  media:
    output: true
    permalink: /media/:name/
  notices:
    output: true
    permalink: /notify/:name/

defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: article
  - scope:
      path: ""
      type: "media"
    values:
      layout: article
  - scope:
      path: ""
      type: "notices"
    values:
      layout: article

exclude:
  - README.md
